language: node_js
node_js:
  - '13'
script:
  - npm test roomManager
before_install:
  - mv ./config/config.sample.json ./config/config.json
install: npm install
services:
  - mongodb
  - redis-server
